### ISSUE TITLE
Custom GIF not displaying correctly

### ISSUE THREAD

**Issue by yskab** [bitbank2/oled_animator#1]
I have this Gif which I generated using GIMP:
![Alt Text](https://github.com/yskab/dhadak/blob/main/spo2.gif?raw=true)

I have used the tcomp tool and generated the array:

./tcomp --in spo2.gif --c --out out.c

But the output is unexpected, I can see the text but it's shifted above and there are junk characters covering the bottom half of the display. I have tried multiple Gifs and scaled them to 128x64, but was not able to get a suitable output.

![Alt Text](https://github.com/yskab/dhadak/blob/main/oled_error.jpeg?raw=true)

Wolf animation works fine which was present in code, could you please help to understand why is this occurring, is this has to do with the way my GIFs are created?

Please ignore the yellow color, I had burned this display with hot air gun.

**Comment by bitbank2** [comment]
I'm sorry that you hit a problem with this code. Unfortunately I no longer support it and will not be fixing it. Since writing an actual GIF animation player for Arduino (AnimatedGIF repo), I no longer support this code. That library requires 23K of RAM to function, but allows the compressed animation data to be much smaller.

**Comment by yskab** [comment]
ah ok got it. I am using Atmega4808, your OneBitDisplay library is suitable for me. 

If possible, could you please provide me the original Wolf Gif that was present in the code? I can see a bin file but that is compressed, if you could please provide the Gif which was used to generate the compressed byte array, it will be helpful, I'll try to perform comparisons or create a new script for compression.

**Comment by bitbank2** [comment]
Unfortunately I no longer have the original file since changing laptops. The compress data format I created is pretty simple and is documented pretty well in the "player" portion of the code in OneBitDisplay.

**Comment by yskab** [comment]
Thanks! I will look at it.
